In [ ]:
import torch

In [ ]:
x = torch.rand(3, requires_grad=True)
y = torch.rand(3, requires_grad=True)

z = x + y
print(z.grad_fn)

s = z.sum()
print(s.grad_fn)

In [ ]:
print(x.grad)
s.backward()
print(x.grad)

In [ ]:
x = torch.rand(3, 4)
y = torch.rand(3, 4)
print(x.requires_grad, y.requires_grad)

z = x + y
print(z.grad_fn)

x.requires_grad_()
y.requires_grad_()
print(x.requires_grad, y.requires_grad)

z = x + y
print(z.grad_fn)
print(z.requires_grad)

detached_z = z.detach()
print(detached_z.grad_fn)

print(x.requires_grad)
print((x + 10).requires_grad)

with torch.no_grad():
    print((x + 10).requires_grad)

print(torch.no_grad)

In [16]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

y = x + 2
print(y)
print(y.grad_fn)

z = y * y * 3
out = z.mean()

print(z, out)
out.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
