In [4]:
import numpy as np
import torch

In [5]:
#Numpy bridge
a = torch.ones(4, 3)
print(a)

b = a.numpy()
print(b)

a.add_(1)
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [6]:
a = np.ones(shape=[3, 4])
b = torch.from_numpy(a)
print(b)

np.add(a, 1, a)
print(a)
print(b)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]], dtype=torch.float64)


In [7]:
#Move the tensor to the cuda
c = torch.rand(3, 4)
print(c)

c = c.cuda()
print(c)

tensor([[0.8681, 0.0716, 0.3054, 0.1507],
        [0.9790, 0.2207, 0.5531, 0.1947],
        [0.5062, 0.3423, 0.0777, 0.6386]])
tensor([[0.8681, 0.0716, 0.3054, 0.1507],
        [0.9790, 0.2207, 0.5531, 0.1947],
        [0.5062, 0.3423, 0.0777, 0.6386]], device='cuda:0')


In [8]:
CUDA = torch.cuda.is_available()

if CUDA:
    c = c.cuda()
    print(c)

tensor([[0.8681, 0.0716, 0.3054, 0.1507],
        [0.9790, 0.2207, 0.5531, 0.1947],
        [0.5062, 0.3423, 0.0777, 0.6386]], device='cuda:0')


In [9]:
#Tensor processes
t1 = torch.rand(3, 4)
t2 = torch.rand(2, 4)

t_result1 = torch.concat([t1, t2], 0)
print(t_result1.shape)

t1 = torch.rand(4, 3)
t2 = torch.rand(4, 7)

t_result1 = torch.concat([t1, t2], 1)
print(t_result1.shape)

torch.Size([5, 4])
torch.Size([4, 10])


In [12]:
#Adding dimension
i_tensor = torch.rand(3)
print(i_tensor)

tensor2 = i_tensor.unsqueeze(0)
print(tensor2, tensor2.size())

tensor3 = i_tensor.unsqueeze(1)
print(tensor3, tensor3.size())

tensor4 = tensor3.unsqueeze(1)
print(tensor4, tensor4.size())
tensor4 = tensor3.unsqueeze(2)
print(tensor4, tensor4.size())


tensor([0.2925, 0.1566, 0.8179])
tensor([[0.2925, 0.1566, 0.8179]]) torch.Size([1, 3])
tensor([[0.2925],
        [0.1566],
        [0.8179]]) torch.Size([3, 1])
tensor([[[0.2925]],

        [[0.1566]],

        [[0.8179]]]) torch.Size([3, 1, 1])
tensor([[[0.2925]],

        [[0.1566]],

        [[0.8179]]]) torch.Size([3, 1, 1])


In [11]:
#Decrement dimension
i_tensor = torch.randn(2, 3, 4)[:, :, 0:2]
print(i_tensor)

tensor5 = i_tensor[:, :, 0:2]
print(tensor5, tensor5.size())

tensor5 = i_tensor[:, 0:2, 0]
print(tensor5, tensor5.size())

tensor5 = i_tensor[:, 0:0, 0:3]
print(tensor5, tensor5.size())


tensor([[[-0.1268, -1.8091],
         [ 0.3776,  0.4154],
         [-0.4087,  0.0739]],

        [[ 0.3265, -0.4884],
         [ 0.3061, -0.7789],
         [-0.1213, -1.1835]]])
tensor([[[-0.1268, -1.8091],
         [ 0.3776,  0.4154],
         [-0.4087,  0.0739]],

        [[ 0.3265, -0.4884],
         [ 0.3061, -0.7789],
         [-0.1213, -1.1835]]]) torch.Size([2, 3, 2])
tensor([[-0.1268,  0.3776],
        [ 0.3265,  0.3061]]) torch.Size([2, 2])
tensor([], size=(2, 0, 2)) torch.Size([2, 0, 2])
