In [ ]:
import torch
import torch.nn as nn

In [ ]:
layer = nn.Linear(5, 5)
print(layer)
print(layer.weight.data)

nn.init.uniform_(layer.weight, 0.0, 3)
print(layer.weight.data)

nn.init.normal_(layer.weight)
print(layer.weight.data.mean(), layer.weight.data.std())
print(layer.weight.data)

nn.init.normal_(layer.weight, 0, 0.2)
print(layer.weight.data.mean(), layer.weight.data.std())
print(layer.weight.data)

In [34]:
nn.init.constant_(layer.bias, 8)
print(layer.bias.data)

nn.init.zeros_(layer.bias)
print(layer.bias.data)

tensor([8., 8., 8., 8., 8.])
tensor([0., 0., 0., 0., 0.])


In [50]:
nn.init.xavier_normal_(layer.weight)
print(layer.weight.data)
print(layer.weight.data.std())

tensor([[ 0.5700,  0.4725,  0.9979,  0.5970,  0.5660],
        [-0.0921, -0.5914,  0.1603, -0.4559,  0.8577],
        [-0.1942, -0.4349, -0.3383,  0.0135, -0.5694],
        [ 0.7470, -0.0685,  0.1131, -0.6687, -0.5611],
        [ 0.2228, -0.6664, -0.2980, -0.3193,  0.6672]])
tensor(0.5268)
